name: presentation
description: "A new Flutter package project."
version: 0.0.1
homepage:
resolution: workspace

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.8.4
  common: 
    path: ../common
  domain:
    path: ../domain
  injectable: ^2.5.0
  get_it: ^8.0.3
  freezed_annotation: ^2.4.4
  bloc: ^8.1.0
  flutter_bloc: ^8.1.2
  bloc_concurrency: ^0.2.3
  rxdart: ^0.27.5
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.0
  auto_route_generator: ^7.3.2
  injectable_generator: ^2.5.0
  freezed: ^2.4.1
  mocktail: ^0.3.0
  bloc_test: ^9.1.1