name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.8.4
  common: ^0.0.1
  presentation:
    path: ../packages/presentation
  injectable: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  injectable_generator: ^2.5.0
  
flutter:
  uses-material-design: true
