name: common
description: Library common module
version: 0.0.1
homepage:
resolution: workspace

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  injectable: ^2.1.0

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
